# Generated by Django 3.2.4 on 2022-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.TimeField(auto_created=True, auto_now=True)),
                ('created_at', models.TimeField(auto_created=True, editable=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('pasword', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('referal_code', models.CharField(max_length=255)),
                ('referred_by', models.BigIntegerField(null=True)),
            ],
        ),
    ]
